### ISSUE TITLE
I can reveive codes from ir control and see them mqtt topics. But I don´t know how to do send an ir control in my TV, air, etc.  Where can I find some exemples?

### ISSUE THREAD

**Issue by 6s1gm4** [enc-X/mqtt-ir-transceiver#6]

**Comment by piotrC4** [comment]
You can do this with openhab like in readme or you can do this by publishing MQTT message:

This example send Global Cache code to device with prefix "esp8266/02"
        
>mosquitto_pub -u <user> -P <password> -h <mqtt_server> -t "esp8266/02/sender/sendGC" -m "38000,1,69,343,172,21,22,21,22,21,65,21,22,21,22,21,22,21,22,21,22,21,65,21,65,21,22,21,65,21,65,21,65,21,65,21,65,21,22,21,65,21,65,21,65,21,22,21,22,21,65,21,65,21,65,21,22,21,22,21,22,21,65,21,65,21,22,21,22,21,1673,343,86,21,3732"

**Comment by 6s1gm4** [comment]
It´s work. I´ll play a lot now. Thanks and congratulations for your work.
