### ISSUE TITLE
ESP-01

### ISSUE THREAD

**Issue by FaustoMendezcom** [enc-X/mqtt-ir-transceiver#8]
Cant get ESP-01 to work I Commented Out #Debug x and selected the esp-01 on the ini file. everything compiles correctly but no AP. if i leave Debug Uncommented  I get wifi I'am able to connect to MQTT but no IR / or Transceiver. Functions.

**Comment by piotrC4** [comment]
In platformio.ini you have to change board parameter to esp01_1m
